/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDeductionsRouteImport } from './routes/_authenticated/deductions'
import { Route as AuthenticatedFeedbackFormsRouteImport } from './routes/_authenticated/feedback-forms'
import { Route as AuthenticatedMyRequestsRouteImport } from './routes/_authenticated/my-requests'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedRequestFormsRouteImport } from './routes/_authenticated/request-forms'
import { Route as AuthenticatedManageFeedbackRouteImport } from './routes/_authenticated/manage.feedback'
import { Route as AuthenticatedManageRequestsRouteImport } from './routes/_authenticated/manage.requests'
import { Route as AuthenticatedSubmitFormIdRouteImport } from './routes/_authenticated/submit.$formId'
import { Route as AuthenticatedManageFormsIndexRouteImport } from './routes/_authenticated/manage.forms.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeductionsRoute = AuthenticatedDeductionsRouteImport.update({
  id: '/deductions',
  path: '/deductions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedbackFormsRoute =
  AuthenticatedFeedbackFormsRouteImport.update({
    id: '/feedback-forms',
    path: '/feedback-forms',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyRequestsRoute = AuthenticatedMyRequestsRouteImport.update({
  id: '/my-requests',
  path: '/my-requests',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRequestFormsRoute =
  AuthenticatedRequestFormsRouteImport.update({
    id: '/request-forms',
    path: '/request-forms',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManageFeedbackRoute =
  AuthenticatedManageFeedbackRouteImport.update({
    id: '/manage/feedback',
    path: '/manage/feedback',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManageRequestsRoute =
  AuthenticatedManageRequestsRouteImport.update({
    id: '/manage/requests',
    path: '/manage/requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubmitFormIdRoute =
  AuthenticatedSubmitFormIdRouteImport.update({
    id: '/submit/$formId',
    path: '/submit/$formId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManageFormsIndexRoute =
  AuthenticatedManageFormsIndexRouteImport.update({
    id: '/manage/forms/',
    path: '/manage/forms/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deductions': typeof AuthenticatedDeductionsRoute
  '/feedback-forms': typeof AuthenticatedFeedbackFormsRoute
  '/my-requests': typeof AuthenticatedMyRequestsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/request-forms': typeof AuthenticatedRequestFormsRoute
  '/manage/feedback': typeof AuthenticatedManageFeedbackRoute
  '/manage/requests': typeof AuthenticatedManageRequestsRoute
  '/submit/$formId': typeof AuthenticatedSubmitFormIdRoute
  '/manage/forms/': typeof AuthenticatedManageFormsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deductions': typeof AuthenticatedDeductionsRoute
  '/feedback-forms': typeof AuthenticatedFeedbackFormsRoute
  '/my-requests': typeof AuthenticatedMyRequestsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/request-forms': typeof AuthenticatedRequestFormsRoute
  '/manage/feedback': typeof AuthenticatedManageFeedbackRoute
  '/manage/requests': typeof AuthenticatedManageRequestsRoute
  '/submit/$formId': typeof AuthenticatedSubmitFormIdRoute
  '/manage/forms': typeof AuthenticatedManageFormsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/deductions': typeof AuthenticatedDeductionsRoute
  '/_authenticated/feedback-forms': typeof AuthenticatedFeedbackFormsRoute
  '/_authenticated/my-requests': typeof AuthenticatedMyRequestsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/request-forms': typeof AuthenticatedRequestFormsRoute
  '/_authenticated/manage/feedback': typeof AuthenticatedManageFeedbackRoute
  '/_authenticated/manage/requests': typeof AuthenticatedManageRequestsRoute
  '/_authenticated/submit/$formId': typeof AuthenticatedSubmitFormIdRoute
  '/_authenticated/manage/forms/': typeof AuthenticatedManageFormsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacy'
    | '/dashboard'
    | '/deductions'
    | '/feedback-forms'
    | '/my-requests'
    | '/notifications'
    | '/request-forms'
    | '/manage/feedback'
    | '/manage/requests'
    | '/submit/$formId'
    | '/manage/forms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacy'
    | '/dashboard'
    | '/deductions'
    | '/feedback-forms'
    | '/my-requests'
    | '/notifications'
    | '/request-forms'
    | '/manage/feedback'
    | '/manage/requests'
    | '/submit/$formId'
    | '/manage/forms'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/privacy'
    | '/_authenticated/dashboard'
    | '/_authenticated/deductions'
    | '/_authenticated/feedback-forms'
    | '/_authenticated/my-requests'
    | '/_authenticated/notifications'
    | '/_authenticated/request-forms'
    | '/_authenticated/manage/feedback'
    | '/_authenticated/manage/requests'
    | '/_authenticated/submit/$formId'
    | '/_authenticated/manage/forms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrivacyRoute: typeof PrivacyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deductions': {
      id: '/_authenticated/deductions'
      path: '/deductions'
      fullPath: '/deductions'
      preLoaderRoute: typeof AuthenticatedDeductionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feedback-forms': {
      id: '/_authenticated/feedback-forms'
      path: '/feedback-forms'
      fullPath: '/feedback-forms'
      preLoaderRoute: typeof AuthenticatedFeedbackFormsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-requests': {
      id: '/_authenticated/my-requests'
      path: '/my-requests'
      fullPath: '/my-requests'
      preLoaderRoute: typeof AuthenticatedMyRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/request-forms': {
      id: '/_authenticated/request-forms'
      path: '/request-forms'
      fullPath: '/request-forms'
      preLoaderRoute: typeof AuthenticatedRequestFormsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manage/feedback': {
      id: '/_authenticated/manage/feedback'
      path: '/manage/feedback'
      fullPath: '/manage/feedback'
      preLoaderRoute: typeof AuthenticatedManageFeedbackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manage/requests': {
      id: '/_authenticated/manage/requests'
      path: '/manage/requests'
      fullPath: '/manage/requests'
      preLoaderRoute: typeof AuthenticatedManageRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/submit/$formId': {
      id: '/_authenticated/submit/$formId'
      path: '/submit/$formId'
      fullPath: '/submit/$formId'
      preLoaderRoute: typeof AuthenticatedSubmitFormIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manage/forms/': {
      id: '/_authenticated/manage/forms/'
      path: '/manage/forms'
      fullPath: '/manage/forms/'
      preLoaderRoute: typeof AuthenticatedManageFormsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDeductionsRoute: typeof AuthenticatedDeductionsRoute
  AuthenticatedFeedbackFormsRoute: typeof AuthenticatedFeedbackFormsRoute
  AuthenticatedMyRequestsRoute: typeof AuthenticatedMyRequestsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedRequestFormsRoute: typeof AuthenticatedRequestFormsRoute
  AuthenticatedManageFeedbackRoute: typeof AuthenticatedManageFeedbackRoute
  AuthenticatedManageRequestsRoute: typeof AuthenticatedManageRequestsRoute
  AuthenticatedSubmitFormIdRoute: typeof AuthenticatedSubmitFormIdRoute
  AuthenticatedManageFormsIndexRoute: typeof AuthenticatedManageFormsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDeductionsRoute: AuthenticatedDeductionsRoute,
  AuthenticatedFeedbackFormsRoute: AuthenticatedFeedbackFormsRoute,
  AuthenticatedMyRequestsRoute: AuthenticatedMyRequestsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedRequestFormsRoute: AuthenticatedRequestFormsRoute,
  AuthenticatedManageFeedbackRoute: AuthenticatedManageFeedbackRoute,
  AuthenticatedManageRequestsRoute: AuthenticatedManageRequestsRoute,
  AuthenticatedSubmitFormIdRoute: AuthenticatedSubmitFormIdRoute,
  AuthenticatedManageFormsIndexRoute: AuthenticatedManageFormsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PrivacyRoute: PrivacyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
