ALTER FUNCTION public.protected_developer_email() SET search_path = public;
REVOKE EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.my_role() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.is_staff() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.is_admin() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.is_developer() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.protected_developer_email() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.write_audit(text, text, text, jsonb) FROM anon, public, authenticated;
REVOKE EXECUTE ON FUNCTION public.bootstrap_profile() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.touch_presence() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.assign_role(text, public.app_role) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.set_authorization(uuid, boolean) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.review_submission(uuid, public.submission_status, text) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.create_deduction(uuid, numeric, text, date, boolean) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.adjust_deduction(uuid, numeric, text, date) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.touch_updated_at() FROM anon, public;

GRANT EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) TO authenticated;
GRANT EXECUTE ON FUNCTION public.my_role() TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_staff() TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_admin() TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_developer() TO authenticated;
GRANT EXECUTE ON FUNCTION public.bootstrap_profile() TO authenticated;
GRANT EXECUTE ON FUNCTION public.touch_presence() TO authenticated;
GRANT EXECUTE ON FUNCTION public.assign_role(text, public.app_role) TO authenticated;
GRANT EXECUTE ON FUNCTION public.set_authorization(uuid, boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.review_submission(uuid, public.submission_status, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_deduction(uuid, numeric, text, date, boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.adjust_deduction(uuid, numeric, text, date) TO authenticated;